#!/usr/bin/env ruby

$LOAD_PATH.push File.dirname(__FILE__)

require 'ec2'

EC2Conn.each_group(ARGV) do |instance|
  puts "#{instance[:tags]["Name"]}	#{instance[:aws_instance_id]}	#{instance[:dns_name]}"
end
